version: '3.3'
services:
    app:
        image: shailesh/awesome-app
        build:
              dockerfile: Dockerfile
              context: .
        environment:
              RAPID_API_KEY: ADD_YOUR_API_KEY
              YH_RAPID_API_URL: https://yh-finance.p.rapidapi.com/stock/v3
        ports:
            - '3000:3000'
